-- GuppiWheel Schema Bootstrap
-- Run this ONCE on a new Snowflake account to create the GuppiWheel infrastructure.
-- Prerequisite: ACCOUNTADMIN or equivalent role.

-- =============================================================================
-- DATABASE + SCHEMA
-- =============================================================================
CREATE DATABASE IF NOT EXISTS GUPPIWHEEL;
CREATE SCHEMA IF NOT EXISTS GUPPIWHEEL.PUBLIC;

-- =============================================================================
-- ARTIFACTS — The single source of truth
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.ARTIFACTS (
    ID          VARCHAR(36)     NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    TYPE        VARCHAR(20)     NOT NULL,
    STAGE       VARCHAR(20)     DEFAULT 'spark',
    PARENT_ID   VARCHAR(36),
    TITLE       VARCHAR(500),
    CONTENT     VARIANT,
    TAGS        ARRAY,
    OWNER       VARCHAR(200),
    CREATED_AT  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    METADATA    VARIANT
);

-- =============================================================================
-- RULES — Governance as data
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.RULES (
    RULE_ID         VARCHAR(30)     NOT NULL PRIMARY KEY,
    RULE_TYPE       VARCHAR(30)     NOT NULL,
    APPLIES_TO_TYPE VARCHAR(30)     DEFAULT 'ALL',
    FROM_STAGE      VARCHAR(20),
    TO_STAGE        VARCHAR(20),
    CONDITION_SQL   VARCHAR(4000)   NOT NULL,
    ENFORCEMENT     VARCHAR(10)     NOT NULL DEFAULT 'warn',
    OVERRIDABLE     BOOLEAN         DEFAULT FALSE,
    MESSAGE         VARCHAR(1000)   NOT NULL,
    ENABLED         BOOLEAN         DEFAULT TRUE,
    VERSION         NUMBER          DEFAULT 1,
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY      VARCHAR(200)    DEFAULT CURRENT_USER()
);

-- =============================================================================
-- VIOLATIONS — Where broken rules land
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.VIOLATIONS (
    VIOLATION_ID    VARCHAR(36)     NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    RULE_ID         VARCHAR(30)     NOT NULL,
    ARTIFACT_ID     VARCHAR(36)     NOT NULL,
    STATUS          VARCHAR(20)     DEFAULT 'open',
    OVERRIDE_REASON VARCHAR(1000),
    DETECTED_AT     TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT     TIMESTAMP_NTZ,
    RESOLVED_BY     VARCHAR(200)
);

-- =============================================================================
-- SEMANTIC VIEWS
-- =============================================================================
CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.INITIATIVES_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:priority::VARCHAR AS PRIORITY,
       METADATA:account::VARCHAR AS ACCOUNT
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'INITIATIVE';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.RESEARCH_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:verdict::VARCHAR AS VERDICT,
       METADATA:source::VARCHAR AS SOURCE
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'RESEARCH';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.STORIES_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:priority::VARCHAR AS PRIORITY,
       METADATA:points::NUMBER AS POINTS
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'STORY';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.APPS_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:app_type::VARCHAR AS APP_TYPE,
       METADATA:url::VARCHAR AS URL
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE IN ('APP', 'MODEL');

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.NARRATIVES_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:narrative_type::VARCHAR AS NARRATIVE_TYPE,
       METADATA:audience::VARCHAR AS AUDIENCE
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'NARRATIVE';

-- =============================================================================
-- RBAC (3-tier)
-- =============================================================================
CREATE ROLE IF NOT EXISTS GUPPIWHEEL_ADMIN;
CREATE ROLE IF NOT EXISTS GUPPIWHEEL_CONTRIBUTOR;
CREATE ROLE IF NOT EXISTS GUPPIWHEEL_VIEWER;

GRANT ROLE GUPPIWHEEL_VIEWER TO ROLE GUPPIWHEEL_CONTRIBUTOR;
GRANT ROLE GUPPIWHEEL_CONTRIBUTOR TO ROLE GUPPIWHEEL_ADMIN;
GRANT ROLE GUPPIWHEEL_ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE GUPPIWHEEL TO ROLE GUPPIWHEEL_VIEWER;
GRANT USAGE ON SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_VIEWER;

GRANT INSERT, UPDATE ON TABLE GUPPIWHEEL.PUBLIC.ARTIFACTS TO ROLE GUPPIWHEEL_CONTRIBUTOR;
GRANT INSERT ON TABLE GUPPIWHEEL.PUBLIC.VIOLATIONS TO ROLE GUPPIWHEEL_CONTRIBUTOR;

GRANT ALL PRIVILEGES ON DATABASE GUPPIWHEEL TO ROLE GUPPIWHEEL_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_ADMIN;
