-- =============================================================================
-- guppi-platform v3.0.0 — Engine Seed 01: Schema
-- Safe to re-run. CREATE OR REPLACE for views, CREATE IF NOT EXISTS for tables.
-- Customer DATA in ARTIFACTS, RULES, VIOLATIONS, ID_CONVENTIONS, INITIATIVE_STEPS,
-- ARTIFACT_LAUNCHES, PLUGIN_VERSION, PRODUCTS — never overwritten by this seed.
-- =============================================================================

-- DATABASE + SCHEMA
CREATE DATABASE IF NOT EXISTS GUPPIWHEEL;
CREATE SCHEMA IF NOT EXISTS GUPPIWHEEL.PUBLIC;
USE DATABASE GUPPIWHEEL;
USE SCHEMA PUBLIC;

-- =============================================================================
-- ARTIFACTS — single source of truth
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.ARTIFACTS (
    ID          VARCHAR(64)     NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    TYPE        VARCHAR(20)     NOT NULL,
    STAGE       VARCHAR(20)     DEFAULT 'Initiate',
    PARENT_ID   VARCHAR(64),
    TITLE       VARCHAR(500),
    CONTENT     VARIANT,
    TAGS        ARRAY,
    OWNER       VARCHAR(200),
    CREATED_AT  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    METADATA    VARIANT
);

-- =============================================================================
-- RULES — governance as data
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.RULES (
    RULE_ID         VARCHAR(30)     NOT NULL PRIMARY KEY,
    RULE_TYPE       VARCHAR(30)     NOT NULL,
    APPLIES_TO_TYPE VARCHAR(30)     DEFAULT 'ALL',
    FROM_STAGE      VARCHAR(20),
    TO_STAGE        VARCHAR(20),
    CONDITION_SQL   VARCHAR(4000)   NOT NULL,
    ENFORCEMENT     VARCHAR(10)     NOT NULL DEFAULT 'warn',
    OVERRIDABLE     BOOLEAN         DEFAULT FALSE,
    MESSAGE         VARCHAR(1000)   NOT NULL,
    ENABLED         BOOLEAN         DEFAULT TRUE,
    VERSION         NUMBER          DEFAULT 1,
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY      VARCHAR(200)    DEFAULT CURRENT_USER()
);

-- =============================================================================
-- VIOLATIONS — where broken rules land
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.VIOLATIONS (
    VIOLATION_ID    VARCHAR(36)     NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    RULE_ID         VARCHAR(30)     NOT NULL,
    ARTIFACT_ID     VARCHAR(64)     NOT NULL,
    STATUS          VARCHAR(20)     DEFAULT 'open',
    OVERRIDE_REASON VARCHAR(1000),
    DETECTED_AT     TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT     TIMESTAMP_NTZ,
    RESOLVED_BY     VARCHAR(200)
);

-- =============================================================================
-- ID_CONVENTIONS — sequence tracker
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.ID_CONVENTIONS (
    ENTITY    VARCHAR(50) NOT NULL PRIMARY KEY,
    NEXT_SEQ  NUMBER      NOT NULL DEFAULT 1,
    NOTES     VARCHAR(500)
);

-- =============================================================================
-- INITIATIVE_STEPS — Rocky step logs
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.INITIATIVE_STEPS (
    STEP_ID         VARCHAR(36)     NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    INITIATIVE_ID   VARCHAR(64)     NOT NULL,
    STEP_NUMBER     NUMBER,
    AGENT_ID        VARCHAR(100),
    ACTION_TYPE     VARCHAR(50),
    PROMPT          VARCHAR,
    RESPONSE        VARCHAR,
    STARTED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT    TIMESTAMP_NTZ,
    METADATA        VARIANT
);

-- =============================================================================
-- PRODUCTS — for Command Center grouping
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.PRODUCTS (
    PRODUCT_ID      VARCHAR(50)     NOT NULL PRIMARY KEY,
    NAME            VARCHAR(200),
    DESCRIPTION     VARCHAR,
    STATUS          VARCHAR(20)     DEFAULT 'active',
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- ARTIFACT_LAUNCHES — audit log of artifact opens
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.ARTIFACT_LAUNCHES (
    LAUNCH_ID     VARCHAR(36)   NOT NULL DEFAULT UUID_STRING() PRIMARY KEY,
    ARTIFACT_ID   VARCHAR(64)   NOT NULL,
    CALLER        VARCHAR(200)  DEFAULT CURRENT_USER(),
    APP_TYPE      VARCHAR(50),
    RESULT_TYPE   VARCHAR(50),
    RESULT_VALUE  VARCHAR(2000),
    TTL_SECONDS   NUMBER,
    EXPIRES_AT    TIMESTAMP_NTZ,
    LAUNCHED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- PLUGIN_VERSION — what's installed
-- =============================================================================
CREATE TABLE IF NOT EXISTS GUPPIWHEEL.PUBLIC.PLUGIN_VERSION (
    PLUGIN_NAME     VARCHAR(100)    NOT NULL PRIMARY KEY,
    VERSION         VARCHAR(20)     NOT NULL,
    INSTALLED_AT    TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    INSTALLED_BY    VARCHAR(200)    DEFAULT CURRENT_USER(),
    NOTES           VARCHAR(500)
);

MERGE INTO GUPPIWHEEL.PUBLIC.PLUGIN_VERSION t
USING (SELECT 'guppi-platform' AS PLUGIN_NAME, '3.0.0' AS VERSION) s
ON t.PLUGIN_NAME = s.PLUGIN_NAME
WHEN MATCHED THEN UPDATE SET VERSION = s.VERSION, INSTALLED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PLUGIN_NAME, VERSION) VALUES (s.PLUGIN_NAME, s.VERSION);

-- =============================================================================
-- ARTIFACT_ASSETS — internal stage for HTML/PDF bytes
-- =============================================================================
CREATE STAGE IF NOT EXISTS GUPPIWHEEL.PUBLIC.ARTIFACT_ASSETS
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Internal stage for artifact bytes (HTML, PDF, static visualizations). Referenced via metadata.launch.stage_path on ARTIFACTS rows.';

-- =============================================================================
-- SENSITIVITY tag
-- =============================================================================
CREATE TAG IF NOT EXISTS GUPPIWHEEL.PUBLIC.SENSITIVITY
  ALLOWED_VALUES 'public', 'internal', 'customer_facing', 'confidential'
  COMMENT = 'Classification of artifact bytes. Drives access policies and audit posture.';

-- =============================================================================
-- TYPE-SPECIFIC VIEWS (optional convenience over the unified ARTIFACTS table)
-- =============================================================================
CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.INITIATIVES_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:priority::VARCHAR AS PRIORITY,
       METADATA:account::VARCHAR AS ACCOUNT
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'INITIATIVE';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.RESEARCH_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       CONTENT:verdict::VARCHAR AS VERDICT
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'RESEARCH';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.STORIES_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:priority::VARCHAR AS PRIORITY,
       METADATA:story_points::NUMBER AS POINTS
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'STORY';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.APPS_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:launch:app_type::VARCHAR AS APP_TYPE,
       METADATA:launch:url::VARCHAR AS URL,
       METADATA:launch:identifier::VARCHAR AS IDENTIFIER
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE IN ('APP','MODEL','DASHBOARD');

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.NARRATIVES_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       METADATA:launch:stage_path::VARCHAR AS STAGE_PATH
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'NARRATIVE';

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.AUDITS_V AS
SELECT ID, STAGE, TITLE, OWNER, CONTENT, TAGS, METADATA, PARENT_ID, CREATED_AT, UPDATED_AT,
       CONTENT:score::FLOAT AS TRUST_SCORE,
       CONTENT:grade::VARCHAR AS GRADE
FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE TYPE = 'AUDIT';

-- =============================================================================
-- RBAC (3-tier)
-- =============================================================================
CREATE ROLE IF NOT EXISTS GUPPIWHEEL_ADMIN;
CREATE ROLE IF NOT EXISTS GUPPIWHEEL_CONTRIBUTOR;
CREATE ROLE IF NOT EXISTS GUPPIWHEEL_VIEWER;

GRANT ROLE GUPPIWHEEL_VIEWER TO ROLE GUPPIWHEEL_CONTRIBUTOR;
GRANT ROLE GUPPIWHEEL_CONTRIBUTOR TO ROLE GUPPIWHEEL_ADMIN;
GRANT ROLE GUPPIWHEEL_ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE GUPPIWHEEL TO ROLE GUPPIWHEEL_VIEWER;
GRANT USAGE ON SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_VIEWER;
GRANT READ ON STAGE GUPPIWHEEL.PUBLIC.ARTIFACT_ASSETS TO ROLE GUPPIWHEEL_VIEWER;

-- CONTRIBUTOR is procedure-mediated: NO direct INSERT/UPDATE on ARTIFACTS (born-locked per RULE-028).
-- Writes flow only through SUBMIT_INITIATIVE / PUBLISH_ARTIFACT / ADVANCE_STAGE / UPDATE_OWN_ARTIFACT
-- (granted in 03_procs.sql, all EXECUTE AS OWNER). Doctrine (RULES, RULES_HISTORY) is ADMIN-ONLY:
-- contributors are intentionally granted NOTHING on those tables. See skill: guppiwheel-governance.
GRANT INSERT ON TABLE GUPPIWHEEL.PUBLIC.VIOLATIONS TO ROLE GUPPIWHEEL_CONTRIBUTOR;       -- proc-written audit trail
GRANT INSERT ON TABLE GUPPIWHEEL.PUBLIC.ARTIFACT_LAUNCHES TO ROLE GUPPIWHEEL_CONTRIBUTOR; -- proc-written
GRANT READ, WRITE ON STAGE GUPPIWHEEL.PUBLIC.ARTIFACT_ASSETS TO ROLE GUPPIWHEEL_CONTRIBUTOR;

GRANT ALL PRIVILEGES ON DATABASE GUPPIWHEEL TO ROLE GUPPIWHEEL_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA GUPPIWHEEL.PUBLIC TO ROLE GUPPIWHEEL_ADMIN;
GRANT READ, WRITE ON STAGE GUPPIWHEEL.PUBLIC.ARTIFACT_ASSETS TO ROLE GUPPIWHEEL_ADMIN;
