-- =============================================================================
-- 10_reconcile.sql — evidence-based capture + ops digest (PLAT-60, v3.31.0)
-- =============================================================================
-- WHY: reminders do not reach the agent in CoCo Desktop (measured 2026-10-06), and
-- GUPPI_TOUCH_WATCH logged "0 touches" on both days of a two-day SnowBeaker build.
-- So detection must observe Snowflake itself: QUERY_HISTORY shows the build work
-- whatever client issued it.
--
-- Evidence kinds (calibrated on 2026-10-05/06 SnowBeaker history):
--   DEPLOY        ALTER WORKSPACE ... ADD LIVE VERSION   (what `snow app deploy` issues)
--   AGENT_RELEASE ALTER AGENT ... SET DEFAULT_VERSION / COMMIT
--   SCHEMA        CREATE [OR REPLACE] TABLE|VIEW|SEMANTIC VIEW|FUNCTION|PROCEDURE in footprint
-- Excluded noise: runtime DML from the app (MERGE INTO PROPOSED_COMPOUNDS = users
-- registering compounds), write_pandas temp stages/tables, grants, SELECTs.
--
-- Debt = evidence in an hour bucket with NO wheel touch (any artifact of that product
-- updated by that user) at or after the evidence. WHEEL ship/story clears it naturally.
-- ACCOUNT_USAGE latency is 45min-3h: this is a backstop, not real-time.
-- =============================================================================

USE SCHEMA GUPPIWHEEL.PUBLIC;

-- Footprints for active build products (extend as products are added).
MERGE INTO GUPPIWHEEL.PUBLIC.PRODUCT_FOOTPRINT t
USING (
            SELECT 'chemlens' P, '%CHEMLENS.%' PAT, 'SnowBeaker DB (codename CHEMLENS)' N
  UNION ALL SELECT 'chemlens', '%CHEMLENS_COPILOT%', 'Beaker agent'
  UNION ALL SELECT 'platform', '%GUPPIWHEEL.PUBLIC.%', 'wheel substrate (DDL only; ARTIFACTS DML excluded)'
  UNION ALL SELECT 'platform', '%GUPPI_LOOP_ENGINE.%', 'loop kernel'
  UNION ALL SELECT 'imaging-dicom', '%DICOM%', 'imaging reference architecture'
  UNION ALL SELECT 'f6', '%NCPDP_F6%', 'F6 claims engine'
) s ON t.PRODUCT_ID = s.P AND t.PATTERN = s.PAT
WHEN NOT MATCHED THEN INSERT (PRODUCT_ID, PATTERN, NOTE) VALUES (s.P, s.PAT, s.N);

-- Raw evidence (owner-rights view over ACCOUNT_USAGE).
CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.WORK_EVIDENCE_V
COMMENT = 'Build-work evidence from QUERY_HISTORY mapped to products via PRODUCT_FOOTPRINT. Kinds: DEPLOY, AGENT_RELEASE, SCHEMA.'
AS
SELECT q.QUERY_ID, q.START_TIME, q.USER_NAME, q.ROLE_NAME, f.PRODUCT_ID,
       CASE
         WHEN q.QUERY_TEXT ILIKE 'ALTER WORKSPACE%ADD LIVE VERSION%' THEN 'DEPLOY'
         WHEN q.QUERY_TEXT ILIKE 'ALTER AGENT%' AND (q.QUERY_TEXT ILIKE '%DEFAULT_VERSION%' OR q.QUERY_TEXT ILIKE '%COMMIT%') THEN 'AGENT_RELEASE'
         ELSE 'SCHEMA'
       END AS KIND,
       LEFT(REGEXP_REPLACE(q.QUERY_TEXT, '\\s+', ' '), 200) AS SAMPLE_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY q
JOIN GUPPIWHEEL.PUBLIC.PRODUCT_FOOTPRINT f ON q.QUERY_TEXT ILIKE f.PATTERN
WHERE q.START_TIME > DATEADD(day, -14, CURRENT_TIMESTAMP())
  AND q.EXECUTION_STATUS = 'SUCCESS'
  AND (
        q.QUERY_TEXT ILIKE 'ALTER WORKSPACE%ADD LIVE VERSION%'
     OR (q.QUERY_TEXT ILIKE 'ALTER AGENT%' AND (q.QUERY_TEXT ILIKE '%DEFAULT_VERSION%' OR q.QUERY_TEXT ILIKE '%COMMIT%'))
     OR (q.QUERY_TYPE IN ('CREATE_TABLE', 'CREATE_TABLE_AS_SELECT', 'CREATE_VIEW', 'CREATE_SEMANTIC_VIEW', 'CREATE_UDF', 'CREATE_PROCEDURE', 'CREATE')
         AND q.QUERY_TEXT ILIKE 'CREATE%'
         AND q.QUERY_TEXT NOT ILIKE '%SNOWPARK_TEMP%'
         AND q.QUERY_TEXT NOT ILIKE 'CREATE TEMP%'
         AND q.QUERY_TEXT NOT ILIKE 'CREATE WORKSPACE%')
  );

-- Reconcile: upsert open debt per (product, kind, user, hour) with no later wheel touch.
CREATE OR REPLACE PROCEDURE GUPPIWHEEL.PUBLIC.WHEEL_RECONCILE(P_LOOKBACK_HOURS NUMBER DEFAULT 72)
RETURNS VARIANT
LANGUAGE SQL
COMMENT = 'Turn WORK_EVIDENCE_V into CAPTURE_DEBT rows when no wheel artifact of that product was touched by that user at/after the evidence. Idempotent.'
EXECUTE AS OWNER
AS
$$
BEGIN
  MERGE INTO GUPPIWHEEL.PUBLIC.CAPTURE_DEBT d
  USING (
    WITH ev AS (
      SELECT PRODUCT_ID, KIND, USER_NAME, DATE_TRUNC('hour', START_TIME) AS BUCKET,
             COUNT(*) AS EVENTS, MIN(START_TIME) AS FIRST_TS, MAX(START_TIME) AS LAST_TS,
             ANY_VALUE(SAMPLE_TEXT) AS SAMPLE_TEXT, ANY_VALUE(QUERY_ID) AS SAMPLE_QUERY_ID
      FROM GUPPIWHEEL.PUBLIC.WORK_EVIDENCE_V
      WHERE START_TIME > DATEADD(hour, -:P_LOOKBACK_HOURS, CURRENT_TIMESTAMP())
      GROUP BY 1, 2, 3, 4
    ),
    touch AS (
      SELECT LOWER(PRODUCT_ID) AS PRODUCT_ID, OWNER AS USER_NAME, MAX(UPDATED_AT) AS LAST_TOUCH
      FROM GUPPIWHEEL.PUBLIC.ARTIFACTS
      WHERE SUPERSEDED_BY IS NULL AND TYPE IN ('STORY', 'DEFECT', 'NARRATIVE', 'APP', 'EPIC', 'INITIATIVE')
      GROUP BY 1, 2
    )
    SELECT ev.PRODUCT_ID || '|' || ev.KIND || '|' || ev.USER_NAME || '|' || TO_VARCHAR(ev.BUCKET, 'YYYY-MM-DD"T"HH24') AS DEBT_KEY,
           ev.*
    FROM ev
    LEFT JOIN touch t ON t.PRODUCT_ID = LOWER(ev.PRODUCT_ID) AND t.USER_NAME = ev.USER_NAME
    WHERE t.LAST_TOUCH IS NULL OR t.LAST_TOUCH::TIMESTAMP_LTZ < ev.LAST_TS
  ) s ON d.DEBT_KEY = s.DEBT_KEY
  WHEN MATCHED AND d.STATUS = 'open' THEN UPDATE SET EVENTS = s.EVENTS, LAST_EVIDENCE_TS = s.LAST_TS
  WHEN NOT MATCHED THEN INSERT (DEBT_KEY, PRODUCT_ID, KIND, USER_NAME, EVENTS, FIRST_EVIDENCE_TS, LAST_EVIDENCE_TS, SAMPLE_TEXT, SAMPLE_QUERY_ID)
    VALUES (s.DEBT_KEY, s.PRODUCT_ID, s.KIND, s.USER_NAME, s.EVENTS, s.FIRST_TS, s.LAST_TS, s.SAMPLE_TEXT, s.SAMPLE_QUERY_ID);

  -- Auto-clear: a later wheel touch for the product by the same user settles older debt.
  UPDATE GUPPIWHEEL.PUBLIC.CAPTURE_DEBT d
     SET STATUS = 'cleared', CLEARED_BY = 'WHEEL_RECONCILE (later wheel touch)', CLEARED_AT = CURRENT_TIMESTAMP()
   WHERE d.STATUS = 'open'
     AND EXISTS (SELECT 1 FROM GUPPIWHEEL.PUBLIC.ARTIFACTS a
                  WHERE a.SUPERSEDED_BY IS NULL AND LOWER(a.PRODUCT_ID) = LOWER(d.PRODUCT_ID)
                    AND a.OWNER = d.USER_NAME AND a.UPDATED_AT::TIMESTAMP_LTZ >= d.LAST_EVIDENCE_TS);

  RETURN OBJECT_CONSTRUCT(
    'open',    (SELECT COUNT(*) FROM GUPPIWHEEL.PUBLIC.CAPTURE_DEBT WHERE STATUS = 'open'),
    'cleared', (SELECT COUNT(*) FROM GUPPIWHEEL.PUBLIC.CAPTURE_DEBT WHERE STATUS = 'cleared'),
    'by_product', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('product', PRODUCT_ID, 'kind', KIND, 'events', N))
                     FROM (SELECT PRODUCT_ID, KIND, SUM(EVENTS) N FROM GUPPIWHEEL.PUBLIC.CAPTURE_DEBT
                            WHERE STATUS = 'open' GROUP BY 1, 2)));
END;
$$;

CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.CAPTURE_DEBT_V AS
SELECT PRODUCT_ID, KIND, USER_NAME, SUM(EVENTS) AS EVENTS, MIN(FIRST_EVIDENCE_TS) AS SINCE,
       MAX(LAST_EVIDENCE_TS) AS LAST_EVIDENCE, ANY_VALUE(SAMPLE_TEXT) AS SAMPLE_TEXT
FROM GUPPIWHEEL.PUBLIC.CAPTURE_DEBT WHERE STATUS = 'open'
GROUP BY 1, 2, 3;

-- One place for operational hygiene. Each row = a check with a count and an example.
CREATE OR REPLACE VIEW GUPPIWHEEL.PUBLIC.OPS_DIGEST_V
COMMENT = 'Operational hygiene digest: capture debt, tripwire hits, stale Building stories, duplicate open initiatives, ID registry conflicts, orphan products.'
AS
SELECT 'capture_debt' AS CHECK_NAME, COUNT(*) AS N, ANY_VALUE(PRODUCT_ID || ': ' || SAMPLE_TEXT) AS EXAMPLE
  FROM GUPPIWHEEL.PUBLIC.CAPTURE_DEBT WHERE STATUS = 'open'
UNION ALL
SELECT 'tripwire_7d', COUNT(*), ANY_VALUE(TARGET_TABLE || ': ' || LEFT(QUERY_TEXT, 120))
  FROM GUPPIWHEEL.PUBLIC.DIRECT_DML_TRIPWIRE_V WHERE START_TIME > DATEADD(day, -7, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'stale_building_stories_7d', COUNT(*), ANY_VALUE(ID || ' ' || TITLE)
  FROM GUPPIWHEEL.PUBLIC.ARTIFACTS
 WHERE TYPE = 'STORY' AND STAGE = 'Building' AND SUPERSEDED_BY IS NULL AND UPDATED_AT < DATEADD(day, -7, CURRENT_TIMESTAMP())
UNION ALL
-- 3.32.0: IDs derive from PRODUCTS.ID_PREFIX; a shared stem would merge two products' series.
SELECT 'product_prefix_shared', COUNT(*), ANY_VALUE(ID_PREFIX)
  FROM (SELECT ID_PREFIX FROM GUPPIWHEEL.PUBLIC.PRODUCTS WHERE ID_PREFIX IS NOT NULL GROUP BY 1 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'product_missing_prefix', COUNT(*), ANY_VALUE(PRODUCT_ID)
  FROM GUPPIWHEEL.PUBLIC.PRODUCTS WHERE ID_PREFIX IS NULL
UNION ALL
SELECT 'duplicate_artifact_ids', COUNT(*), ANY_VALUE(ID)
  FROM (SELECT ID FROM GUPPIWHEEL.PUBLIC.ARTIFACTS GROUP BY 1 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'products_missing_from_registry', COUNT(*), ANY_VALUE(P)
  FROM (SELECT DISTINCT LOWER(PRODUCT_ID) P FROM GUPPIWHEEL.PUBLIC.ARTIFACTS WHERE PRODUCT_ID IS NOT NULL
        MINUS SELECT LOWER(PRODUCT_ID) FROM GUPPIWHEEL.PUBLIC.PRODUCTS);

GRANT SELECT ON VIEW GUPPIWHEEL.PUBLIC.CAPTURE_DEBT_V TO ROLE GUPPIWHEEL_CONTRIBUTOR;
GRANT SELECT ON VIEW GUPPIWHEEL.PUBLIC.OPS_DIGEST_V   TO ROLE GUPPIWHEEL_CONTRIBUTOR;
GRANT USAGE ON PROCEDURE GUPPIWHEEL.PUBLIC.WHEEL_RECONCILE(NUMBER) TO ROLE GUPPIWHEEL_ADMIN;

-- Hourly backstop. Serverless; ACCOUNT_USAGE latency means "hourly" ~= 1-3h behind.
CREATE OR REPLACE TASK GUPPIWHEEL.PUBLIC.WHEEL_RECONCILE_TASK
  SCHEDULE = '60 MINUTE'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  COMMENT = 'Hourly evidence-based capture reconcile (PLAT-60).'
AS
  CALL GUPPIWHEEL.PUBLIC.WHEEL_RECONCILE(72);

ALTER TASK GUPPIWHEEL.PUBLIC.WHEEL_RECONCILE_TASK RESUME;
